name: Release
on:
  push:
    branches:
      -  master
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'New Tag'
        required: true  

      prev_tag:
        description: 'Prev Tag'
        required: true  

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v3
        with:
          ref: master
      - name: "✏️ Generate release changelog"
        id: generate_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: CHANGELOG.md
          futureRelease: "1.0.1"
          dateFormat: "%m/%d/%Y"
      - name: Commit changes
        id: commit_changelog
        timeout-minutes: 1
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update CHANGELOG.md'
          branch: master
      - name: Instal Convertor
        run: npm install showdown -g
      - name: Convert md to html
        run: showdown makehtml -i .\CHANGELOG.md -o .\CHANGELOG.html    
      - name: Extract new changes
        id: extract_change
        run: |
          echo ::set-output name=changelog::$(cat CHANGELOG.html)
      
      - name: test
        id: tt
        run: |
          echo ${{steps.extract_change.outputs.changelog}}
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: "1.0.0"
          body: "<p> ${{steps.extract_change.outputs.changelog}} </p> "
          commit: ${{ steps.commit_changelog.outputs.commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
