name: On pre-release
on:
  release:
    types: [prereleased]

  # Optionally you can use `workflow_dispatch` to run Changelog CI Manually
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Set Tag'
        required: true  

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v3
        with:
          ref: master
      - name: "✏️ Generate release changelog"
        id: generate_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: CHANGELOG.md
          futureRelease: ${{ github.event.inputs.tag_name }}
          dateFormat: "%m/%d/%Y"
      - name: Commit changes
        id: commit_changelog
        timeout-minutes: 1
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update CHANGELOG.md'
          branch: master
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          body: ${{ steps.generate_changelog.outputs.stdout }}
          commit: ${{ steps.commit_changelog.outputs.commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
